### ISSUE TITLE
建议：希望能增加桌面歌词功能

### ISSUE THREAD

**Issue by fcsnsu** [lovegaoshi/azusa-player-mobile#111]
功能需求：桌面歌词
平台：安卓移动端
说明：希望能增加桌面歌词功能，因为听歌一般都是挂在后台，但只有在播放器里才能看到歌词，挂在后台就看不到了

**Comment by lovegaoshi** [comment]
兄弟你看我像是会写桌面歌词的人吗，做个安卓车机都要死要活的

https://github.com/lyswhut/lx-music-mobile/issues/30
https://github.com/lyswhut/lx-music-mobile/commit/53ea75977878329a56d612b4c52ff6e54d556e17
https://github.com/lyswhut/lx-music-mobile/commits/master?before=d8d9f7022f35b2f79714f649a80c76ea73943162+525&branch=master&qualified_name=refs%2Fheads%2Fmaster

**Comment by lovegaoshi** [comment]
lx音乐的桌面歌词UX得打开关闭不好使，用画中画做
