### ISSUE TITLE
ios 播放错误

### ISSUE THREAD

**Issue by kanshufan-1107** [lovegaoshi/azusa-player-mobile#127]
ios 播放错误 提示failed to load resource

![image](https://github.com/lovegaoshi/azusa-player-mobile/assets/53857697/10cde840-5249-4b6e-99c8-b549a76f07c7)

**Comment by lovegaoshi** [comment]
@kenmingwang 来修bug了

**Comment by lovegaoshi** [comment]
应该是https://upos-sz-mirroraliov.bilivideo.com 相关错误
1. 用https://github.com/lovegaoshi/azusa-player-mobile/releases/tag/v2.3.2
2.设置 -> 开发者选项 -> 置日志等级 ->调试
3. 播放一首错误歌
4. 设置 -> 开发者选项 -> 日志
5. 找 `[SongResolveURL] ${song.name} is resolved to ${url.url}` 贴到这里

**Comment by kanshufan-1107** [comment]
日志没有一键复制，错误日志如下
[SongResolveURL](4K&amp:1080P修复] 周杰伦-《反方向的钟》MV完整版 is resolved to https://xy123x175x209x26xy.mcdn.bilivideo.cn:8082/v1/resource737230626 nb3-1-30280.m4s?agrr=1&build=0&buvid=&bvc=vod&bv=40247&deadline=1691983117&e=ig8euxZM2rNcNbdlhoNvNC8BaJIzNbfaxBvEgxTEto8BTrNVNOGVT90W5JZMkxYNOMvXg8gNEV4NC8xNEV4N03eNCB5tZlaNxTEto8BTrNvNeZVuJ10Ki g2UB02J0mN0B5tZlaNCNEto8BTrNvNC7MTX502C8f2imMQJ6mgF2fka1mqx6gqjOeNOB599M%3D&gen=playurlv2&ogo=A0000002&mcdnid=2003242&md=0&nbs=1&nettype=0&oi=3027051806&orderid=0%2C3&os=mcdn&platform=pc&sign=7a97e7&traceid=triWXQzKCHYi 0 e N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=536fef5e6418b925735ef5a73e10f4b5

**Comment by kanshufan-1107** [comment]
日志弹窗没有一键复制😮‍💨，以下是播放的错误日志
[SongResolveURL](4K&amp:1080P修复] 周杰伦-《反方向的钟》MV完整版 is resolved to 
http://xy123x175x209x26xy.mcdn.bilivideo.cn:8082/v1/resource/737230626_nb3-1-30280.m4s?agrr=1&build=0&buvid=&bvc=vod&bw=40247&deadline=1691983117&e=ig8euxZM2rNcNbdlhoNvNC8BaJIzNbfaxBvEgxTEto8BTrNVNOGVT90W5JZMkx_YNOMvXg8gNEV4NC8xNEV4N03eN0B5tZlaNxTEto8BTrNvNeZVuJ10Ki_g2UB02J0mN0B5tZlaNCNEto8BTrNvNC7MTX502C8f2imMQJ6mgF2fka1mqx6gqjOeNOB599M%3D&gen=playurlv2&logo=A0000002&mcdnid=2003242&mid=0&nbs=1&nettype=0&oi=3027051806&orderid=0%2C3&os=mcdn&platform=pc&sign=7a97e7&traceid=triWXQzfKCHYi_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=536fef5e6418b925735ef5a73e10f4b5

**Comment by kanshufan-1107** [comment]
日志弹窗没有一键复制😮‍💨，以下是播放的错误日志
[SongResolveURL](4K&amp:1080P修复] 周杰伦-《反方向的钟》MV完整版 is resolved to
https://xy123x175x209x26xy.mcdn.bilivideo.cn:8082/v1/resource/737230626_nb3-1-30280.m4s?agrr=1&build=0&buvid=&bvc=vod&bw=40247&deadline=1691983117&e=ig8euxZM2rNcNbdlhoNvNC8BaJIzNbfaxBvEgxTEto8BTrNVNOGVT90W5JZMkx_YNOMvXg8gNEV4NC8xNEV4N03eN0B5tZlaNxTEto8BTrNvNeZVuJ10Ki_g2UB02J0mN0B5tZlaNCNEto8BTrNvNC7MTX502C8f2imMQJ6mgF2fka1mqx6gqjOeNOB599M%3D&gen=playurlv2&logo=A0000002&mcdnid=2003242&mid=0&nbs=1&nettype=0&oi=3027051806&orderid=0%2C3&os=mcdn&platform=pc&sign=7a97e7&traceid=triWXQzfKCHYi_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=536fef5e6418b925735ef5a73e10f4b5
