### ISSUE TITLE
求大佬弄个MusicFree适配的APM

### ISSUE THREAD

**Issue by sykeswzq** [lovegaoshi/azusa-player-mobile#277]
求大佬弄个MusicFree适配的APM，麻瓜不会弄，只能在线求助大佬适配

**Comment by lovegaoshi** [comment]
APM存了MF官方源，但是不好使
![Screenshot_20240121_203206_APM](https://github.com/lovegaoshi/azusa-player-mobile/assets/106490582/bb5c8999-7e8a-4e37-9735-1844ba7b7362)
![Screenshot_20240121_203212_APM](https://github.com/lovegaoshi/azusa-player-mobile/assets/106490582/0a00ceb6-6971-4ac8-ad7c-52a40de92837)

**Comment by sykeswzq** [comment]
收到，感谢
