### ISSUE TITLE
收藏夹里的音频投稿无法识别

### ISSUE THREAD

**Issue by RengeRenge** [lovegaoshi/azusa-player-mobile#279]
比如这首 https://www.bilibili.com/audio/au769254

希望能识别音频投稿，谢谢！

**Comment by lovegaoshi** [comment]
会在下一个版本和[开发版本](https://github.com/lovegaoshi/azusa-player-mobile/releases)里喔。

**Comment by RengeRenge** [comment]
> 会在下一个版本和[开发版本](https://github.com/lovegaoshi/azusa-player-mobile/releases)里喔。

OKK，爱你哟
