### ISSUE TITLE
[bug] BV1DZ4y1G7JK 播放闪退

### ISSUE THREAD

**Issue by Zheng9710** [lovegaoshi/azusa-player-mobile#292]
手机是魅族18s，感觉不仅是app闪退，回到桌面图标都过了一会才显示，好像是整个系统都卡住然后重启了的感觉

**Comment by Zheng9710** [comment]
卸载后重新安装正常，但从dropbox下载备份的歌单后版本号就会从最新版本变成2.12.6，然后就会卡住闪退

**Comment by lovegaoshi** [comment]
dropbox的noxbackup文件麻烦发来看看

**Comment by Zheng9710** [comment]
https://www.dropbox.com/scl/fi/xdu1gb9fv6coplbhgjmk3/nox.noxBackup?rlkey=kcttt2xvg047g886g5qbp9gb4&dl=0
这是备份文件
然后在不下载备份歌单的情况下连续听大概十几首歌也会发生以上情况，在断网情况下打开app则正常启动，重连网络暂时正常

**Comment by Zheng9710** [comment]
试了大概三十次 总是在同一首歌的地方卡住闪退，歌单第14首 牵丝戏下面是B站地址
https://www.bilibili.com/video/BV1DZ4y1G7JK/?p=1&vd_source=3f7709806303416cdd7b0ca169637ce8
卡住的时候能播放，但是进度条始终不动且app卡住无法操作，三四秒后闪退，之后无法启动，断网后重开正常，但问题依旧存在

**Comment by lovegaoshi** [comment]
我超还真是，我的也炸了

**Comment by Zheng9710** [comment]
![image](https://github.com/lovegaoshi/azusa-player-mobile/assets/36422659/b9b60052-33b5-4e7d-a78c-45bd35f7f193)
在电脑上用MUMU模拟器导入歌单后正常使用，但版本号显示是2.12.6
![image](https://github.com/lovegaoshi/azusa-player-mobile/assets/36422659/8af55f7e-7c89-40bd-b22b-ab047a7dec3e)
app应用信息里的版本号则是2.12.9

**Comment by lovegaoshi** [comment]
这个没事儿 第二次启动就会升到最新版本号
黄龄这个没看懂 研究一下

**Comment by Zheng9710** [comment]
好好 辛苦了

**Comment by lovegaoshi** [comment]
我的APM也炸了。。。应该是你的歌单上一次停到了牵丝戏，然后打开APM时一直尝试恢复到牵丝戏上 然后一直爆炸
模拟器也炸了，但是莫名其妙又好了
下载的缓存文件放到别人的播放器里还能放，我是最气的
不知道怎么搞牵丝戏 安卓崩溃选择性重启倒是要抬上日程

**Comment by Zheng9710** [comment]
那就期待之后的版本更新啦

**Comment by lovegaoshi** [comment]
牵丝戏搞不懂 不搞了
