### ISSUE TITLE
[Feature]Extension and Mobile PlayLists Sync?

### ISSUE THREAD

**Issue by kenmingwang** [lovegaoshi/azusa-player-mobile#38]
Simple cloud storage to allow user do periodic Sync between web Extension lists and Mobile list?

**Comment by lovegaoshi** [comment]
yep, working on it. 
i used to have cloud backup options via dropbox & a simple private cloud server, can msg u the app secret later:
https://github.com/lovegaoshi/azusa-player/blob/nox-player/src/components/buttons/syncing/DropboxSyncButton.js
https://github.com/lovegaoshi/azusa-player/blob/nox-player/src/utils/dropboxauth.js
it was taking user's bilibili user ID as key/filename. im done with bilibili login now so getting the id for cloud backup would be possible

had a very vague idea of how to import from extension's sync, obviously didnt fully flush out
https://github.com/lovegaoshi/azusa-player-mobile/blob/master/src/utils/ChromeStorage.ts#L285

**Comment by lovegaoshi** [comment]
如果要使用dropbox-sdk-js，需要删除其中导入 crypto 和 util这两个包裹。这两个包裹用来新建PKCE/oauth2的链接地址，但是我用https://www.npmjs.com/package/react-native-app-auth不需要。
已成功用react-native-app-auth登录dropbox
https://github.com/FormidableLabs/react-native-app-auth/issues/772

**Comment by lovegaoshi** [comment]
歌单导入导出做好了，用Dev的apk https://github.com/lovegaoshi/azusa-player-mobile/releases/tag/dev-build-2023-05-26
我为了解决上传文件效率在我插件版做了压缩，就是很简单的fflate。在https://github.com/kenmingwang/azusa-player/commit/a07cdc15d8f007a94f3b6892ca94d780fdb40fc7

电梓播放器直接拷贝storage.js的修改内容应该就可

nox有dropbox同步选项 azusa可以先用手机版上传dropbox创建app文件夹，再本地导出，改名为nox.noxbackup 上传dropbox 再用手机下载
