### ISSUE TITLE
不能提取收藏夹歌单

### ISSUE THREAD

**Issue by 2328228963** [lovegaoshi/azusa-player-mobile#387]
如题，不同于PC插件，移动端虽然能加入合集，但不能添加收藏夹里的歌单，希望能添加此功能

**Comment by lovegaoshi** [comment]
什么链接在PC端可以加，手机卜行？这俩用的是一个玩意儿

**Comment by 2328228963** [comment]
嘶，突然可以了，上周不知道哪不对，还是谢谢了♪(･ω･)ﾉ
