### ISSUE TITLE
ios版本添加到歌单失败

### ISSUE THREAD

**Issue by cuivic** [lovegaoshi/azusa-player-mobile#395]
2.15.0版本添加到歌单时不显示歌单名称
![BFB8A886-447C-4600-9E68-1C5849CB17A5](https://github.com/lovegaoshi/azusa-player-mobile/assets/102679895/14c24d65-9b82-4adb-9e59-7593f31267c7)

**Comment by lovegaoshi** [comment]
暂时多加几个歌单看看

**Comment by cuivic** [comment]
确实可以了，谢谢
