### ISSUE TITLE
播放器能添加几款纯色皮肤吗

### ISSUE THREAD

**Issue by cuivic** [lovegaoshi/azusa-player-mobile#396]
照顾下非二次元的感受🥲

**Comment by lovegaoshi** [comment]
管人痴的确有股味，大概下版本可能会也许内嵌一个纯色的

皮肤支持自己做，太想要可以写一个纯色的进去

**Comment by cuivic** [comment]
也想自己做一个，奈何水平有限...

**Comment by lovegaoshi** [comment]
jian: erciyuan ssw
![image](https://github.com/lovegaoshi/azusa-player-mobile/assets/106490582/f443484f-22a3-4b9f-9f2d-cc2a9504ff00)
