### ISSUE TITLE
ios 运行问题

### ISSUE THREAD

**Issue by ElonXun** [lovegaoshi/azusa-player-mobile#400]
你好 
我用 mac 运行 yarn ios会报
error Could not find scheme example. Please make sure the schema you want to run exists. Available schemas are: APM'.
请问应该怎么弄才能 正常run 起来？

yarn 1.22.22

**Comment by lovegaoshi** [comment]
xcode打开文件夹运行；命令行yarn start

**Comment by ElonXun** [comment]
感谢！跑起来了
原来是少了 xcode打开文件夹运行 这步
