### ISSUE TITLE
Carplay support?

### ISSUE THREAD

**Issue by pixelkoduje** [lovegaoshi/azusa-player-mobile#408]
Do you support Carplay?  Are you developing using pure React Native or Expo?

**Comment by lovegaoshi** [comment]
I dont have an iphone and personally dislike apple with a passion; I recommend u refer to the wonderful RN-carplay community at https://github.com/birkir/react-native-carplay/issues/175 and for a FOSS app implemented RNTP and carplay, [podverse/podverse-rn: Podverse mobile app written in React Native for iOS, Android, and F-Droid](https://github.com/podverse/podverse-rn)
