### ISSUE TITLE
歌曲合集的歌单只能播放第一首？

### ISSUE THREAD

**Issue by bwxz** [lovegaoshi/azusa-player-mobile#447]
歌曲合集的歌单只能播放第一首吗？比如别人整理了几十首的歌合集，只会播放 第一个

**Comment by lovegaoshi** [comment]
什么合集的url会这样

**Comment by bwxz** [comment]
https://www.bilibili.com/video/BV1Vc411M7kB/?spm_id_from=333.999.0.0
这样的，听起来好尴尬啊

**Comment by lovegaoshi** [comment]
![Screenshot_20240526_232933_APM](https://github.com/lovegaoshi/azusa-player-mobile/assets/106490582/9938d787-0c87-43de-b73d-47f24cbcd72d)
并没有这个问题啊

**Comment by bwxz** [comment]
原来如此：用网址是可以的，搜名字的那种不行

**Comment by lovegaoshi** [comment]
搜索分p的支持在 设置 一般设置 快速b站搜索那里打开
