### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [lovegaoshi/azusa-player-mobile#502]
Can I package this app for F-Droid?

**Comment by lovegaoshi** [comment]
sure thing, appreciate the work!

**Comment by linsui** [comment]
I'll have a try. :)

**Comment by linsui** [comment]
The build failed without a clear error. https://gitlab.com/linsui/fdroiddata/-/jobs/7199886552 Any idea?

**Comment by lovegaoshi** [comment]
is there a way to get the output of 
`node /home/vagrant/build/com.noxplay.noxplayer/node_modules/@react-native-community/cli/build/bin.js config`? im seeing a json format of some info of packages used.

**Comment by linsui** [comment]
```
error Failed to build the app: No package name found. We couldn't parse the namespace from neither your build.gradle[.kts] file at null nor your package in the AndroidManifest at /home/vagrant/build/com.noxplay.noxplayer/node_modules/react-native-blob-util/android/src/main/AndroidManifest.xml.
```

**Comment by lovegaoshi** [comment]
i have no idea:S does this patch fix? https://github.com/lovegaoshi/azusa-player-mobile/commit/320f920b76357f1bd7990f9d4ae5718accdacb23 from branch https://github.com/lovegaoshi/azusa-player-mobile/tree/dev-fdroid

**Comment by linsui** [comment]
You have some good ideas, it works! :) https://gitlab.com/linsui/fdroiddata/-/jobs/7210653702 Now we need to build those abis one by one. Can you add something like https://github.com/SwissBitcoinPay/app/blob/main/android/app/build.gradle#L87C5-L87C29 and https://github.com/SwissBitcoinPay/app/blob/main/android/app/build.gradle#L143?

**Comment by lovegaoshi** [comment]
i believe its already split
https://github.com/lovegaoshi/azusa-player-mobile/blob/320f920b76357f1bd7990f9d4ae5718accdacb23/android/app/build.gradle#L88

and added the version code u mentioned
https://github.com/lovegaoshi/azusa-player-mobile/blob/b86c815b549d6b3de61ce4e5c85f623a8cabf009/android/app/build.gradle#L131

**Comment by linsui** [comment]
> and added the version code u mentioned

Thanks!

> i believe its already split

Yep, but F-Droid needs to build the apks one by one so we need to set the abi for every build. I can patch the file but it would be better if I can set the abi easily. :)

**Comment by lovegaoshi** [comment]
sry im not understanding here; the only diff i see is i specified
universalAPK to be true (which splits but also adds a universal apk) do u
mean that has to be off or im missing something else?

**Comment by linsui** [comment]
Currently it builds 5 apks at the same time. But F-Droid needs to build them one by one. This is my current metadata. https://gitlab.com/linsui/fdroiddata/-/commit/ed3cdcc574de3c70dc825667e616b0a615c6e1a1 I patched the include line to build one the armv7 abi.

**Comment by lovegaoshi** [comment]
ah ok! updated now.
https://github.com/lovegaoshi/azusa-player-mobile/commit/718bbf2fa48ca19489be81a656252c1b4d3e33fa

**Comment by linsui** [comment]
Thanks! It builds and works for me.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15290 It will be available on fdroid.org in few day. Thanks for your help!

**Comment by lovegaoshi** [comment]
tysm! do u know if i can make an automatic fdroid update ghactions file? i can attach it to my automatic release actions. thx again!

**Comment by linsui** [comment]
You don't need to do that. See the bottom of the metadata file. Autoupdate is already enabled. When you tag a new release, the metadata will be updated automatically.

**Comment by lovegaoshi** [comment]
cool thank you!

**Comment by lovegaoshi** [comment]
awesome thank you again! one last ques. does auto-update track the fdroid branch (i assume so?) or main?

**Comment by linsui** [comment]
It only tracks the tags. Will you merge the fdroid branch into master?

**Comment by lovegaoshi** [comment]
ah ok. i can add that in the release action. appreciate it!

**Comment by linsui** [comment]
Please tell me when it's done. I'll tweak the auto update config. Thanks!

**Comment by lovegaoshi** [comment]
i added this in the ghactions build file. please see https://github.com/lovegaoshi/azusa-player-mobile/commit/580cd01a7b045ebd2a6d7774eb1afc41dfc7bfe0 (v2.17.7-fdroid tag)
does this work?

**Comment by linsui** [comment]
It works, thanks!

**Comment by linsui** [comment]
Hmmm, I'm confused. You have merged those changes for F-Droid into master. Then why do we need special tags for F-Droid?

**Comment by lovegaoshi** [comment]
trying to keep the version codes right - i update the version codes in ghactions via a push

**Comment by linsui** [comment]
Ah, OK. :)
