### ISSUE TITLE
请问有没有不要自动重播的模式？

### ISSUE THREAD

**Issue by garyyeap** [lovegaoshi/azusa-player-mobile#544]
新人刚下载使用，主要是想把视频转成音频当 podcast 省流用，不是拿来听音乐，两个问题：
1.  类似骰子的图案是随机播放的意思？那么另一个打叉是？
2. 试过所有模式全部都会重复播放(列表只有一个曲目的情况下)？如果是的话，是不是可以加一个播放完毕就结束的模式？

**Comment by lovegaoshi** [comment]
骰子是下一个播放从b站或油管视频推荐里随机
叉是传统意义的随机播放
我只用列表循环 不循环没做

**Comment by lovegaoshi** [comment]
![image](https://github.com/user-attachments/assets/ec75edcb-52ea-4517-a417-ff2f8edea610)
