### ISSUE TITLE
关于无法下载文件的问题

### ISSUE THREAD

**Issue by laoling123** [lovegaoshi/azusa-player-mobile#560]
您好，想问一下apm在使用过程中无法下载文件是怎么回事呢？输入bv号后可以正常播放，但是点击下载后虽然显示了已下载，但是在music文件夹里面没有apm的相关文件夹，整个手机的文件中也没有搜到。在使用过程中也授予了软件相关权限，看了评论区发现也不止一位用户遇到类似的情况，因此想问一下解决方式，我使用的设备为红米note13pro![1726736211343.jpg](https://github.com/user-attachments/assets/d4596c1a-7449-4f28-a16c-844de7c8e543)

**Comment by lovegaoshi** [comment]
debug: "[ffmpeg] additionally inserting cover art..."
debug: "[ffmpeg] ffmpeg to mp3 command: -i '/data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_74td7w1e44c7s6sqk45sn9.m4s' -vn -ab 256k -id3v2_version 3 -metadata title='【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》' -metadata artist='Megalo_PaleWhite' -metadata album='【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》' /data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_74td7w1e44c7s6sqk45sn9.m4s.mp3"
debug: "Changing Seasons -Reload- is no longer the active track."
debug: "[r128gain] set r128gain to -1.05 dB"
debug: "[r128gain] found saved r128gain as -1.05"
debug: "Changing Seasons -Reload- is no longer the active track."
debug: "[cache] Changing Seasons -Reload- completed. now clearing cache and set R128gain..."
debug: "[r128gain] set r128gain to -1.05 dB"
debug: "[FFMPEG] now starting FFMPEG r128gain..."
debug: "[cache] /data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_urgkmwuxmjt9hfrtsiit89.785 is being purged as its not used."
debug: "Changing Seasons -Reload- caching progress: 97%"
debug: "Changing Seasons -Reload- caching progress: 95%"
debug: "Changing Seasons -Reload- caching progress: 92%"
debug: "Changing Seasons -Reload- caching progress: 90%"
debug: "Changing Seasons -Reload- caching progress: 87%"
debug: "Changing Seasons -Reload- caching progress: 85%"
debug: "Changing Seasons -Reload- caching progress: 82%"
debug: "Changing Seasons -Reload- caching progress: 80%"
debug: "Changing Seasons -Reload- caching progress: 77%"
debug: "Changing Seasons -Reload- caching progress: 74%"
debug: "Changing Seasons -Reload- caching progress: 72%"
debug: "Changing Seasons -Reload- caching progress: 69%"
debug: "Changing Seasons -Reload- caching progress: 67%"
debug: "Changing Seasons -Reload- caching progress: 64%"
debug: "Changing Seasons -Reload- caching progress: 61%"
debug: "Changing Seasons -Reload- caching progress: 59%"
debug: "Changing Seasons -Reload- caching progress: 56%"
debug: "Changing Seasons -Reload- caching progress: 54%"
debug: "Changing Seasons -Reload- caching progress: 51%"
debug: "Changing Seasons -Reload- caching progress: 48%"
debug: "Changing Seasons -Reload- caching progress: 46%"
debug: "Changing Seasons -Reload- caching progress: 43%"
debug: "Changing Seasons -Reload- caching progress: 41%"
debug: "Changing Seasons -Reload- caching progress: 38%"
debug: "Changing Seasons -Reload- caching progress: 35%"
debug: "Changing Seasons -Reload- caching progress: 32%"
debug: "Changing Seasons -Reload- caching progress: 29%"
debug: "Changing Seasons -Reload- caching progress: 27%"
debug: "Changing Seasons -Reload- caching progress: 24%"
debug: "Changing Seasons -Reload- caching progress: 21%"
debug: "Changing Seasons -Reload- caching progress: 19%"
debug: "Changing Seasons -Reload- caching progress: 16%"
debug: "Changing Seasons -Reload- caching progress: 13%"
debug: "Changing Seasons -Reload- caching progress: 11%"
debug: "Changing Seasons -Reload- caching progress: 8%"
debug: "Changing Seasons -Reload- caching progress: 5%"
debug: "Changing Seasons -Reload- caching progress: 0%"
debug: "Changing Seasons -Reload- caching progress: 0%"
debug: "[Cache] fetching 【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》 to cache..."
debug: "[resolver] resolved BV18z421z7Yf to https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/70/27/1596682770/1596682770-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1726772570&gen=playurlv2&os=aliovbv&oi=1185180348&trid=5fb45bf67e9848e5bef7b9b3b1af133du&mid=0&platform=pc&og=cos&upsig=510e4db4aa58b63c3f83a465a6d206b4&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&f=u_0_0&agrr=0&bw=27034&logo=80000000"
debug: "[SongResolveURL] Changing Seasons -Reload- is resolved to https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/70/27/1596682770/1596682770-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1726772570&gen=playurlv2&os=aliovbv&oi=1185180348&trid=5fb45bf67e9848e5bef7b9b3b1af133du&mid=0&platform=pc&og=cos&upsig=510e4db4aa58b63c3f83a465a6d206b4&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&f=u_0_0&agrr=0&bw=27034&logo=80000000"
debug: "[wbiQuery] https://api.bilibili.com/x/player/wbi/playurl?bvid=BV18z421z7Yf&cid=1596682770&fnval=16&qn=64&try_look=1&voice_balance=1&wts=1726765370&w_rid=985d7fdba3ef189fc2ecdceb4112e64d"
debug: "[resolveURL] cid resolved to be: 1596682770"
debug: "fethcVideoPlayURL: https://api.bilibili.com/x/player/wbi/playurl?cid=null-BV18z421z7Yf&bvid=BV18z421z7Yf&qn=64&fnval=16&try_look=1&voice_balance=1 with AudioUrl"
debug: "[resolveURL] BV18z421z7Yf, null-BV18z421z7Yf }"
debug: "[CacheResolveURL] Changing Seasons -Reload- needs to be refetched."
debug: "[SongResolveURL] cache missed, null-BV18z421z7Yf"
debug: "[SongResolveURL] start resolving 【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》"

**Comment by lovegaoshi** [comment]
暂时怀疑你没有打开缓存功能 所以失败

**Comment by laoling123** [comment]
> 暂时怀疑你没有打开缓存功能 所以失败

可以了，已经解决了，麻烦您了_(:з」∠)_

**Comment by laoling123** [comment]
> 请把日志等级调整为 调试  然后下载 粘贴日志daozheli
> 这是三星可以正常下载的日志
> ```
> debug: "[ffmpeg] additionally inserting cover art..."
> debug: "[ffmpeg] ffmpeg to mp3 command: -i '/data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_74td7w1e44c7s6sqk45sn9.m4s' -vn -ab 256k -id3v2_version 3 -metadata title='【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》' -metadata artist='Megalo_PaleWhite' -metadata album='【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》' /data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_74td7w1e44c7s6sqk45sn9.m4s.mp3"
> debug: "Changing Seasons -Reload- is no longer the active track."
> debug: "[r128gain] set r128gain to -1.05 dB"
> debug: "[r128gain] found saved r128gain as -1.05"
> debug: "Changing Seasons -Reload- is no longer the active track."
> debug: "[cache] Changing Seasons -Reload- completed. now clearing cache and set R128gain..."
> debug: "[r128gain] set r128gain to -1.05 dB"
> debug: "[FFMPEG] now starting FFMPEG r128gain..."
> debug: "[cache] /data/user/0/com.noxplay.noxplayer/files/ReactNativeBlobUtilTmp_urgkmwuxmjt9hfrtsiit89.785 is being purged as its not used."
> debug: "Changing Seasons -Reload- caching progress: 97%"
> debug: "Changing Seasons -Reload- caching progress: 95%"
> debug: "Changing Seasons -Reload- caching progress: 92%"
> debug: "Changing Seasons -Reload- caching progress: 90%"
> debug: "Changing Seasons -Reload- caching progress: 87%"
> debug: "Changing Seasons -Reload- caching progress: 85%"
> debug: "Changing Seasons -Reload- caching progress: 82%"
> debug: "Changing Seasons -Reload- caching progress: 80%"
> debug: "Changing Seasons -Reload- caching progress: 77%"
> debug: "Changing Seasons -Reload- caching progress: 74%"
> debug: "Changing Seasons -Reload- caching progress: 72%"
> debug: "Changing Seasons -Reload- caching progress: 69%"
> debug: "Changing Seasons -Reload- caching progress: 67%"
> debug: "Changing Seasons -Reload- caching progress: 64%"
> debug: "Changing Seasons -Reload- caching progress: 61%"
> debug: "Changing Seasons -Reload- caching progress: 59%"
> debug: "Changing Seasons -Reload- caching progress: 56%"
> debug: "Changing Seasons -Reload- caching progress: 54%"
> debug: "Changing Seasons -Reload- caching progress: 51%"
> debug: "Changing Seasons -Reload- caching progress: 48%"
> debug: "Changing Seasons -Reload- caching progress: 46%"
> debug: "Changing Seasons -Reload- caching progress: 43%"
> debug: "Changing Seasons -Reload- caching progress: 41%"
> debug: "Changing Seasons -Reload- caching progress: 38%"
> debug: "Changing Seasons -Reload- caching progress: 35%"
> debug: "Changing Seasons -Reload- caching progress: 32%"
> debug: "Changing Seasons -Reload- caching progress: 29%"
> debug: "Changing Seasons -Reload- caching progress: 27%"
> debug: "Changing Seasons -Reload- caching progress: 24%"
> debug: "Changing Seasons -Reload- caching progress: 21%"
> debug: "Changing Seasons -Reload- caching progress: 19%"
> debug: "Changing Seasons -Reload- caching progress: 16%"
> debug: "Changing Seasons -Reload- caching progress: 13%"
> debug: "Changing Seasons -Reload- caching progress: 11%"
> debug: "Changing Seasons -Reload- caching progress: 8%"
> debug: "Changing Seasons -Reload- caching progress: 5%"
> debug: "Changing Seasons -Reload- caching progress: 0%"
> debug: "Changing Seasons -Reload- caching progress: 0%"
> debug: "[Cache] fetching 【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》 to cache..."
> debug: "[resolver] resolved BV18z421z7Yf to https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/70/27/1596682770/1596682770-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1726772570&gen=playurlv2&os=aliovbv&oi=1185180348&trid=5fb45bf67e9848e5bef7b9b3b1af133du&mid=0&platform=pc&og=cos&upsig=510e4db4aa58b63c3f83a465a6d206b4&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&f=u_0_0&agrr=0&bw=27034&logo=80000000"
> debug: "[SongResolveURL] Changing Seasons -Reload- is resolved to https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/70/27/1596682770/1596682770-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1726772570&gen=playurlv2&os=aliovbv&oi=1185180348&trid=5fb45bf67e9848e5bef7b9b3b1af133du&mid=0&platform=pc&og=cos&upsig=510e4db4aa58b63c3f83a465a6d206b4&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&f=u_0_0&agrr=0&bw=27034&logo=80000000"
> debug: "[wbiQuery] https://api.bilibili.com/x/player/wbi/playurl?bvid=BV18z421z7Yf&cid=1596682770&fnval=16&qn=64&try_look=1&voice_balance=1&wts=1726765370&w_rid=985d7fdba3ef189fc2ecdceb4112e64d"
> debug: "[resolveURL] cid resolved to be: 1596682770"
> debug: "fethcVideoPlayURL: https://api.bilibili.com/x/player/wbi/playurl?cid=null-BV18z421z7Yf&bvid=BV18z421z7Yf&qn=64&fnval=16&try_look=1&voice_balance=1 with AudioUrl"
> debug: "[resolveURL] BV18z421z7Yf, null-BV18z421z7Yf }"
> debug: "[CacheResolveURL] Changing Seasons -Reload- needs to be refetched."
> debug: "[SongResolveURL] cache missed, null-BV18z421z7Yf"
> debug: "[SongResolveURL] start resolving 【P3R歌词翻译】《Changing Seasons -Reload-》/《季节流转 -Reload-》"
> ```


可以了，已经解决了，麻烦您了_(:з」∠)_
