### ISSUE TITLE
请问，作者您知道手机上在app内更新，它下载到什么路径吗？

### ISSUE THREAD

**Issue by Mudrockiii** [lovegaoshi/azusa-player-mobile#567]
更新之后只会提示下载完成，不会弹出来安装页面，也找不到安装包在哪里。

**Comment by lovegaoshi** [comment]
pixel机型在系统APP->下载管理器的里面
三丧不知道
其他机型不知道

下载完成以后需要你手动点那个完成 然后会进入更新提示。不点的话就没了
自动更新更推荐你用fdroid和play store
