### ISSUE TITLE
无法连接油管听歌

### ISSUE THREAD

**Issue by Jade888wang** [lovegaoshi/azusa-player-mobile#578]
安卓，无法连接油管听歌，翻墙也不行，听歌界面显示Source error
![IMG_20241016_111403](https://github.com/user-attachments/assets/9e50f698-2027-47b8-bd61-9cfb68c66565)

**Comment by lovegaoshi** [comment]
你的版本号？
油管六月份杀了一批下载器 apm之前用的也在其中
请确认是在用2.18.1 因为我的能用
![Uploading Screenshot_20241015_202144_APM.jpg…]()

**Comment by lovegaoshi** [comment]
![Screenshot_20241015_202144_APM](https://github.com/user-attachments/assets/8dc0f19d-5ebd-4534-9fb8-06032480b3a0)

**Comment by lovegaoshi** [comment]
油管最近大封了很多机房ip ghactions也被封了
除了找小机场基本无解 ytdlp有一些魔法但是也基本无法解决 资本家也没余粮
有些甚至传cookie都用不了
我本人的机房ip也被封了

**Comment by Jade888wang** [comment]
如果能把这个问题根除那apm就是音乐播放器界的唯一真神了
原理是跟YouTube music差不多吧，都是通过视频网站来获取音频的，要是有破译版的ytmusic解除后台听歌限制那我就apm，ytmusic一起用了hhhh
前段时间用spotify一开始觉得挺好用，后面就没法自己选歌听了欸，这年头想完美听个歌好难

**Comment by lovegaoshi** [comment]
后台ytm用revanced系
https://revanced.net/revanced-youtube-music-extended

和github搜索 innertune

ios不太清楚

APM对于油管的支持比较答辩 这个本来是用来订阅b站合集的

**Comment by Jade888wang** [comment]
好的，谢谢！apm目前看来已经很好用了，但还是期待后续的更新完善😁✊我觉得要是能更方便的自主换主题背景就更好了😎
