### ISSUE TITLE
collectiondetail & seriesdetail

### ISSUE THREAD

**Issue by SH-ke** [lovegaoshi/azusa-player-mobile#589]
支持的格式：https://space.bilibili.com/36908799/channel/seriesdetail?sid=3085578
不支持的格式：https://space.bilibili.com/3493093607213343/channel/collectiondetail?sid=3836622
我遇到了一种不太一样的合集url,貌似不是分p合集，不知道作者是否能够支持这一种格式？
I have encountered a different collection URL, which seems to be not a split p collection. I wonder if the owner @lovegaoshi can support this format?

**Comment by lovegaoshi** [comment]
支持 但你没登录
