### ISSUE TITLE
歌单备份失败，已经登录dropbox，仍然提示需要登录。

### ISSUE THREAD

**Issue by cuivic** [lovegaoshi/azusa-player-mobile#592]
error: "JSON Parse error: Unexpected character: <"
debug: "dropbox token expired, need to log in"
warn: "[sync] auth failed:DropboxResponseError: Response failed with a 400 code"
error: "{\"type\":\"cancel\"}"
debug: "dropbox token expired, need to log in"
warn: "[sync] auth failed:DropboxResponseError: Response failed with a 400 code"

**Comment by lovegaoshi** [comment]
没法复现
日志显示你取消了登录

**Comment by lovegaoshi** [comment]
无回复
