### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [lovegaoshi/azusa-player-mobile#593]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8138666650#L3487 looks like a dep (skia?) needs ndk 27?

@linsui can you take a look?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/5ef1af2c6def16b921fc72840dcaa0af7d95bc08

**Comment by linsui** [comment]
Then we just bump it?

**Comment by licaon-kter** [comment]
The main project uses 26, didn't get a chance to test, but usually it might fail later. I was thinking we need to add it (27 Android_ndk path) in `build:` then remove it maybe.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/8144620025 Lol

**Comment by lovegaoshi** [comment]
i do see both ndk26 and 27 are used, [but ghactions can build fine for some reason](https://github.com/lovegaoshi/azusa-player-mobile/actions/runs/11431174267/job/31799791563)

**Comment by licaon-kter** [comment]
@linsui yes that's the one

Hence my thinking we can make a combo of ndk: 26, in build rm 26, install 27, export 27, then reinstall 26 so after build when env is reset, it's used.

**Comment by linsui** [comment]
Fixed.
